### ISSUE TITLE
rgbaToRgb is not a function

### ISSUE THREAD

**Issue by Gopalakrishnan-V** [iyegoroff/rgba-to-rgb#1]
When I try to use the package in Node.js, I am getting the following error.

const RGB_color = rgbaToRgb(RGB_background, RGBA_color);
                                                   ^
**TypeError: rgbaToRgb is not a function**

Below is my code: 
const rgbaToRgb = require("rgba-to-rgb");

const RGB_background = "rgb(255, 120, 5)";
const RGBA_color = "rgba(123, 233, 33, 0.5)";
const RGB_color = rgbaToRgb(RGB_background, RGBA_color);

**Comment by iyegoroff** [comment]
Try `const rgbaToRgb = require("rgba-to-rgb").default`
